---
# - name: Verify that required parameters are set
#   ansible.builtin.assert:
#     that:
#       - '{{ item.key }} is defined'
#       - '{{ item.key }} | length > 0'
#   with_items:
#     - { 'key': realm }
#     - { 'key': ntp }
...
